/* My Loan Tracker V4 - built on the stable V3.5 data model. */
const configured = typeof window.SUPABASE_URL === "string" && typeof window.SUPABASE_ANON_KEY === "string" && !window.SUPABASE_URL.includes("YOUR_") && !window.SUPABASE_ANON_KEY.includes("YOUR_") && typeof window.supabase !== "undefined";
const sb = configured ? window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY) : null;
let loans = [], paymentCache = {}, editingLoanId = null, signup = false;
const $ = id => document.getElementById(id);
const money = n => new Intl.NumberFormat("en-IN", {style:"currency", currency:"INR", maximumFractionDigits:2}).format(Number(n)||0);
const today = () => new Date().toISOString().slice(0,10);
const fmt = d => d ? new Date(d+"T00:00:00").toLocaleDateString("en-IN") : "Not set";
const addMonths = (s,m) => { const d=new Date(s+"T00:00:00"), day=d.getDate(); d.setMonth(d.getMonth()+m); if(d.getDate()!==day)d.setDate(0); return d.toISOString().slice(0,10); };
const frequencyMonths = f => f==="quarterly"?3:f==="halfyearly"?6:12;
const interest = l => { const annual=(Number(l.principal)||0)*(Number(l.interest_rate)||0)/100; return l.frequency==="quarterly"?annual/4:l.frequency==="halfyearly"?annual/2:annual; };
function notice(t){$("notice").textContent=t;$("notice").classList.remove("hidden");setTimeout(()=>$("notice").classList.add("hidden"),4500)}
function esc(s){return String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));}
function isOverdue(l){return !!(l.due_date && l.due_date<today());}
function parseNotes(raw){const s=raw||"";const m=s.match(/^\[\[category:([^\]]+)\]\]\s*/i);return {category:m?m[1]:"Other",note:m?s.slice(m[0].length):s};}
function packNotes(category,note){return `[[category:${category||"Other"}]]${note?" "+note:""}`;}
function fields(){const e=$("type").value==="emi";$("emiFields").classList.toggle("hidden",!e);$("intFields").classList.toggle("hidden",e);$("emiDateFields").classList.toggle("hidden",!e);$("emi").required=e;$("dueDate").required=!e;$("emiDueDate").required=e;}
async function load(){
  const r=await sb.from("loans").select("*").order("created_at"); if(r.error){notice(r.error.message);return;}
  loans=r.data||[];paymentCache={};
  if(loans.length){const p=await sb.from("payments").select("*").in("loan_id",loans.map(x=>x.id)).order("payment_date",{ascending:false});if(p.error){notice(p.error.message);return;}for(const row of p.data||[])(paymentCache[row.loan_id]??=[]).push(row);}
  render();
}
function ps(id){return paymentCache[id]||[];}
function totals(id){const p=ps(id);return {interest:p.filter(x=>x.payment_type==="interest").reduce((a,x)=>a+Number(x.amount||0),0),principal:p.filter(x=>x.payment_type==="principal").reduce((a,x)=>a+Number(x.amount||0),0),payments:p};}
function trackedPrincipal(l){return Number(l.principal||0)+totals(l.id).principal;}
function categories(){const set=new Set(["Bank","Gold Loan","Agricultural","Personal","Housing","Vehicle","Other"]);loans.forEach(l=>set.add(parseNotes(l.notes).category));$("categoryFilter").innerHTML='<option value="all">All categories</option>'+[...set].sort().map(c=>`<option>${esc(c)}</option>`).join("");}
function filtered(){const q=$("search").value.trim().toLowerCase(), f=$("filter").value,c=$("categoryFilter").value;return loans.filter(l=>{const n=parseNotes(l.notes);const match=!q||l.name.toLowerCase().includes(q)||n.note.toLowerCase().includes(q);const type=f==="all"||l.loan_type===f||(f==="overdue"&&isOverdue(l));return match&&type&&(c==="all"||n.category===c);});}
function render(){
  categories();
  const outstanding=loans.reduce((a,l)=>a+Number(l.principal||0),0), emi=loans.filter(l=>l.loan_type==="emi").reduce((a,l)=>a+Number(l.emi||0),0), intOnly=loans.filter(l=>l.loan_type==="interest").reduce((a,l)=>a+Number(l.principal||0),0), due=loans.filter(l=>l.loan_type==="interest").reduce((a,l)=>a+interest(l),0), paidInterest=loans.reduce((a,l)=>a+totals(l.id).interest,0), paidPrincipal=loans.reduce((a,l)=>a+totals(l.id).principal,0), tracked=loans.reduce((a,l)=>a+trackedPrincipal(l),0), pct=tracked?Math.min(100,paidPrincipal/tracked*100):0;
  $("total").textContent=money(outstanding);$("emiTotal").textContent=money(emi);$("intTotal").textContent=money(intOnly);$("dueTotal").textContent=money(due);$("paidTotal").textContent=money(paidInterest);$("overdueTotal").textContent=loans.filter(isOverdue).length;
  $("principalTracked").textContent=money(tracked);$("principalPaid").textContent=money(paidPrincipal);$("progressPct").textContent=pct.toFixed(1)+"%";$("progressBar").style.width=pct+"%";
  const debtFree=estimateDebtFree();$("debtFreeDate").textContent=debtFree?fmt(debtFree):"—";$("overviewText").textContent=`${loans.length} active loan${loans.length===1?"":"s"} • ${money(outstanding)} principal outstanding`;
  const box=$("loans"), list=filtered();box.innerHTML="";
  if(!list.length){box.innerHTML=`<div class="card">${loans.length?"No loans match your search/filter.":"No loans yet. Click + Add Loan to begin."}</div>`;}else list.forEach(l=>box.appendChild(loanCard(l)));
  renderReports();renderCalendar();populateSimulator();
}
function loanCard(l){
  const t=totals(l.id), meta=parseNotes(l.notes), dueInterest=l.loan_type==="interest"?interest(l):0, prog=trackedPrincipal(l)?Math.min(100,t.principal/trackedPrincipal(l)*100):0;
  const a=document.createElement("article");a.className="card loan";
  const status=l.loan_type==="interest"?(isOverdue(l)?'<span class="badge overdue">Overdue</span>':'<span class="badge ok">On track</span>'):'<span class="badge">Monthly EMI</span>';
  a.innerHTML=`<div class="loanTop"><div><h3>${esc(l.name)}</h3><span class="badge">${l.loan_type==="emi"?"EMI Loan":"Interest Only"}</span><span class="badge category">${esc(meta.category)}</span></div><strong class="balance">${money(l.principal)}</strong></div>
  <div class="details">${l.loan_type==="emi"?`Monthly EMI: <b>${money(l.emi)}</b><br>Rate: <b>${l.interest_rate}% p.a.</b><br>Next EMI: <b>${fmt(l.due_date)}</b>`:`Rate: <b>${l.interest_rate}% p.a.</b><br>${esc(l.frequency)} interest: <b>${money(dueInterest)}</b><br>Next due: <b>${fmt(l.due_date)}</b> ${status}`}</div>
  <div class="loanProgress"><div style="width:${prog}%"></div></div><small>Principal paid in this tracker: ${money(t.principal)} (${prog.toFixed(1)}%)</small>
  <div class="payment-summary"><div class="mini">Interest paid<b>${money(t.interest)}</b></div><div class="mini">Principal paid<b>${money(t.principal)}</b></div><div class="mini">${l.loan_type==="interest"?"Current interest":"Next EMI"}<b>${l.loan_type==="interest"?money(dueInterest):money(l.emi)}</b></div></div>
  <div class="actions"><button data-a="pay">Record Payment</button>${l.loan_type==="emi"?'<button data-a="schedule" class="schedule-btn">Schedule</button><button data-a="sim">What-if</button>':''}<button data-a="edit">Edit</button><button data-a="history">History</button><button data-a="del" class="danger">Delete</button></div><div class="history hidden"></div>`;
  a.querySelector('[data-a="pay"]').onclick=()=>showPay(l.id);a.querySelector('[data-a="edit"]').onclick=()=>showEdit(l.id);a.querySelector('[data-a="history"]').onclick=()=>showHistory(l.id);a.querySelector('[data-a="del"]').onclick=()=>deleteLoan(l.id);if(l.loan_type==="emi"){a.querySelector('[data-a="schedule"]').onclick=()=>showSchedule(l.id);a.querySelector('[data-a="sim"]').onclick=()=>showSimulator(l.id);}return a;
}
function showAdd(){editingLoanId=null;$("loanTitle").textContent="Add Loan";$("loanForm").reset();$("type").value="interest";fields();$("loanSec").classList.remove("hidden");hideSections("loanSec");$("loanSec").classList.remove("hidden");$("loanSec").scrollIntoView({behavior:"smooth"});}
function showEdit(id){const l=loans.find(x=>x.id===id);if(!l)return;editingLoanId=id;const n=parseNotes(l.notes);$("loanTitle").textContent="Edit Loan";$("name").value=l.name;$("category").value=n.category;$("type").value=l.loan_type;$("principal").value=l.principal;$("rate").value=l.interest_rate;$("emi").value=l.emi||"";$("frequency").value=l.frequency||"yearly";$("dueDate").value=l.loan_type==="interest"?(l.due_date||""):"";$("emiDueDate").value=l.loan_type==="emi"?(l.due_date||""):"";$("notes").value=n.note;fields();hideSections("loanSec");$("loanSec").classList.remove("hidden");$("loanSec").scrollIntoView({behavior:"smooth"});}
function hideSections(keep){["paySec","scheduleSec","historySec","simSec"].filter(x=>x!==keep).forEach(x=>$(x).classList.add("hidden"));}
async function deleteLoan(id){if(!confirm("Delete this loan and all its payment history?"))return;const r=await sb.from("loans").delete().eq("id",id);if(r.error)notice(r.error.message);else await load();}
function showSchedule(id){const l=loans.find(x=>x.id===id);if(!l||l.loan_type!=="emi")return;let bal=Number(l.principal)||0, emi=Number(l.emi)||0, mr=(Number(l.interest_rate)||0)/1200,date=l.due_date||today(),rows=[],ti=0,tp=0,n=0;if(bal<=0){$("scheduleBox").innerHTML="<b>This loan is fully paid.</b>";}else if(emi<=0){$("scheduleBox").innerHTML="<b>Set a monthly EMI greater than zero.</b>";}else{while(bal>.005&&n<600){n++;const opening=bal,ip=opening*mr,pay=Math.min(emi,opening+ip),pp=Math.max(0,pay-ip);bal=Math.max(0,opening-pp);ti+=ip;tp+=pay;rows.push({n,date,opening,ip,pay,pp,bal});date=addMonths(date,1);}$("scheduleBox").innerHTML=`<div class="schedule-head"><div class="mini">Current balance<b>${money(l.principal)}</b></div><div class="mini">Future interest<b>${money(ti)}</b></div><div class="mini">Future payments<b>${money(tp)}</b></div></div><p>Estimated ${rows.length} payments. Assumes rate and EMI remain unchanged.</p><div style="overflow:auto"><table class="schedule-table"><thead><tr><th>#</th><th>Date</th><th>Opening</th><th>Interest</th><th>EMI</th><th>Principal</th><th>Closing</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.n}</td><td>${fmt(r.date)}</td><td>${money(r.opening)}</td><td>${money(r.ip)}</td><td>${money(r.pay)}</td><td>${money(r.pp)}</td><td>${money(r.bal)}</td></tr>`).join("")}</tbody></table></div>`;}hideSections("scheduleSec");$("scheduleSec").classList.remove("hidden");$("scheduleSec").scrollIntoView({behavior:"smooth"});}
function showPay(id){const l=loans.find(x=>x.id===id);if(!l)return;$("payLoanId").value=id;$("payLoanName").textContent=l.name;$("payDate").value=today();$("amount").value=l.loan_type==="emi"?l.emi:"";$("payType").value="interest";$("payNote").value="";const e=l.loan_type==="emi";$("payTitle").textContent=e?"Record EMI Payment":"Record Payment";$("payTypeWrap").classList.toggle("hidden",e);$("emiPaymentHelp").classList.toggle("hidden",!e);$("emiSplit").classList.toggle("hidden",!e);if(e)updateEmiSplit();hideSections("paySec");$("paySec").classList.remove("hidden");$("paySec").scrollIntoView({behavior:"smooth"});}
function updateEmiSplit(){const l=loans.find(x=>x.id===$("payLoanId").value);if(!l)return;const amt=Number($("amount").value)||0,ip=Math.min(amt,Math.max(0,(Number(l.principal)||0)*(Number(l.interest_rate)||0)/1200)),pp=Math.max(0,amt-ip);$("emiInterest").textContent=money(ip);$("emiPrincipal").textContent=money(pp);}
function showHistory(id){const l=loans.find(x=>x.id===id);if(!l)return;$("historyTitle").textContent=`Payment History — ${l.name}`;const p=ps(id);$("historyBox").innerHTML=p.length?`<div class="historyRows">${p.map(x=>`<div class="historyRow"><div><b>${fmt(x.payment_date)}</b> — ${money(x.amount)}<br><small>${esc(x.payment_type)}${x.note?" — "+esc(x.note):""}</small></div><div class="historyActions"><button data-edit="${x.id}">Edit</button><button data-del="${x.id}" class="danger">Delete</button></div></div>`).join("")}</div>`:"No payments recorded.";p.forEach(x=>{$(`[data-edit="${x.id}"]`).onclick=()=>editPayment(x.id);$(`[data-del="${x.id}"]`).onclick=()=>deletePayment(x.id);});hideSections("historySec");$("historySec").classList.remove("hidden");$("historySec").scrollIntoView({behavior:"smooth"});}
function groupId(note){const m=(note||"").match(/\[\[group:([^\]]+)\]\]/);return m?m[1]:null;}
function groupRows(row){const g=groupId(row.note);if(g)return ps(row.loan_id).filter(x=>groupId(x.note)===g);const same=ps(row.loan_id).filter(x=>x.payment_date===row.payment_date);const pair=same.find(x=>x.id!==row.id&&((x.note||"").startsWith("EMI ")||x.note?.includes("EMI ")));return pair?[row,pair]:[row];}
async function editPayment(id){const row=psForId(id);if(!row)return;const l=loans.find(x=>x.id===row.loan_id);const rows=groupRows(row);if(rows.length>1){const oldPrincipal=rows.filter(x=>x.payment_type==="principal").reduce((a,x)=>a+Number(x.amount||0),0),preBalance=Number(l.principal||0)+oldPrincipal;const amount=prompt(`Enter the corrected total EMI for ${fmt(row.payment_date)}:`,String(rows.reduce((a,x)=>a+Number(x.amount||0),0)));if(amount===null)return;const amt=Number(amount);if(!(amt>0))return notice("Enter a positive amount.");const ip=Math.min(amt,preBalance*(Number(l.interest_rate)||0)/1200),pp=Math.max(0,amt-ip),g=groupId(row.note)||crypto.randomUUID();const baseNote=(row.note||"").replace(/^EMI (interest|principal)\s*/i,"").replace(/\[\[group:[^\]]+\]\]/,"").trim();const r=await sb.from("payments").update({amount:ip,note:`[[group:${g}]]EMI interest${baseNote?" — "+baseNote:""}`}).eq("id",rows.find(x=>x.payment_type==="interest").id);if(r.error)return notice(r.error.message);const r2=await sb.from("payments").update({amount:pp,note:`[[group:${g}]]EMI principal${baseNote?" — "+baseNote:""}`}).eq("id",rows.find(x=>x.payment_type==="principal").id);if(r2.error)return notice(r2.error.message);const u=await sb.from("loans").update({principal:Math.max(0,preBalance-pp)}).eq("id",l.id);if(u.error)return notice(u.error.message);await load();showHistory(l.id);return;}
  const amount=prompt("Correct amount:",String(row.amount));if(amount===null)return;const amt=Number(amount);if(!(amt>0))return notice("Enter a positive amount.");if(row.payment_type==="principal"){const delta=Number(row.amount)-amt;const u=await sb.from("loans").update({principal:Math.max(0,Number(l.principal)+delta)}).eq("id",l.id);if(u.error)return notice(u.error.message);}const r=await sb.from("payments").update({amount:amt}).eq("id",id);if(r.error)return notice(r.error.message);await load();showHistory(l.id);}
function psForId(id){for(const arr of Object.values(paymentCache)){const x=arr.find(p=>p.id===id);if(x)return x;}return null;}
async function deletePayment(id){const row=psForId(id);if(!row||!confirm("Delete this payment?"))return;const l=loans.find(x=>x.id===row.loan_id),rows=groupRows(row);if(rows.length>1){const pp=rows.filter(x=>x.payment_type==="principal").reduce((a,x)=>a+Number(x.amount||0),0);const u=await sb.from("loans").update({principal:Number(l.principal)+pp}).eq("id",l.id);if(u.error)return notice(u.error.message);const d=await sb.from("payments").delete().in("id",rows.map(x=>x.id));if(d.error)return notice(d.error.message);}else{if(row.payment_type==="principal"){const u=await sb.from("loans").update({principal:Number(l.principal)+Number(row.amount)}).eq("id",l.id);if(u.error)return notice(u.error.message);}const d=await sb.from("payments").delete().eq("id",id);if(d.error)return notice(d.error.message);}await load();showHistory(l.id);}
function estimateDebtFree(){let dates=[];loans.filter(l=>l.loan_type==="emi"&&Number(l.emi)>0&&Number(l.principal)>0).forEach(l=>{let b=Number(l.principal),mr=Number(l.interest_rate)/1200,n=0;while(b>.005&&n<600){const ip=b*mr,p=Math.min(Number(l.emi),b+ip),pp=Math.max(0,p-ip);b=Math.max(0,b-pp);n++;}if(l.due_date)dates.push(addMonths(l.due_date,n-1));});return dates.length?dates.sort().pop():null;}
function showSimulator(id){$("simLoan").value=id;$("simEmi").value="";$("simExtra").value=0;$("simDate").value=today();$("simResult").innerHTML="";hideSections("simSec");$("simSec").classList.remove("hidden");$("simSec").scrollIntoView({behavior:"smooth"});}
function simulate(l,emi,extra){let b=Math.max(0,Number(l.principal)-extra),mr=Number(l.interest_rate)/1200,n=0,interestSum=0;while(b>.005&&n<600){const ip=b*mr,p=Math.min(emi,b+ip),pp=Math.max(0,p-ip);interestSum+=ip;b=Math.max(0,b-pp);n++;}return {months:n,interest:interestSum,end:n&&l.due_date?addMonths(l.due_date,n-1):null};}
function runSimulator(){const l=loans.find(x=>x.id===$("simLoan").value);if(!l)return;const base=simulate(l,Number(l.emi)||0,0),newEmi=Number($("simEmi").value)||Number(l.emi)||0,extra=Number($("simExtra").value)||0,alt=simulate(l,newEmi,extra);const savedI=Math.max(0,base.interest-alt.interest),savedM=Math.max(0,base.months-alt.months);$("simResult").innerHTML=`<div class="compare"><div class="card"><b>Current plan</b><p>EMI: ${money(l.emi)}<br>Time: ${base.months} months<br>Future interest: ${money(base.interest)}<br>Estimated finish: ${fmt(base.end)}</p></div><div class="card"><b>What-if plan</b><p>EMI: ${money(newEmi)}<br>Extra principal: ${money(extra)}<br>Time: ${alt.months} months<br>Future interest: ${money(alt.interest)}<br>Estimated finish: ${fmt(alt.end)}</p></div></div><p><b>Potential saving:</b> ${money(savedI)} interest and ${savedM} month${savedM===1?"":"s"}.</p>`;}
function renderReports(){const month=new Date().toISOString().slice(0,7),year=new Date().getFullYear().toString(),pm=loans.flatMap(l=>ps(l.id));const monthRows=pm.filter(p=>p.payment_date.startsWith(month)),yearRows=pm.filter(p=>p.payment_date.startsWith(year));const totalPaid=pm.reduce((a,p)=>a+Number(p.amount||0),0),monthPaid=monthRows.reduce((a,p)=>a+Number(p.amount||0),0),yearPaid=yearRows.reduce((a,p)=>a+Number(p.amount||0),0),futureInterest=loans.filter(l=>l.loan_type==="emi").reduce((a,l)=>a+simulate(l,Number(l.emi)||0,0).interest,0);$("reportsBox").innerHTML=[[`Active loans`,loans.length], ["Payments recorded",pm.length],["All-time paid",money(totalPaid)],["This month",money(monthPaid)],["This year",money(yearPaid)],["Principal paid",money(pm.filter(p=>p.payment_type==="principal").reduce((a,p)=>a+Number(p.amount||0),0))],["Interest paid",money(pm.filter(p=>p.payment_type==="interest").reduce((a,p)=>a+Number(p.amount||0),0))],["Estimated future EMI interest",money(futureInterest)]].map(x=>`<div class="reportCard"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");}
function renderCalendar(){const start=new Date();start.setDate(1);const events=[];for(let i=0;i<3;i++){const d=new Date(start.getFullYear(),start.getMonth()+i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;for(const l of loans){if(!l.due_date)continue;let cur=l.due_date;const step=l.loan_type==="emi"?1:frequencyMonths(l.frequency);for(let n=0;n<36&&cur.slice(0,7)<=key;n++){if(cur.slice(0,7)===key)events.push({date:cur,loan:l,kind:l.loan_type==="emi"?"EMI":`${l.frequency} interest`});cur=addMonths(cur,step);}}}const months=[];for(let i=0;i<3;i++){const d=new Date(start.getFullYear(),start.getMonth()+i,1),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,title=d.toLocaleDateString("en-IN",{month:"long",year:"numeric"});const es=events.filter(e=>e.date.startsWith(key)).sort((a,b)=>a.date.localeCompare(b.date));months.push(`<div class="monthCard"><h3>${title}</h3>${es.length?es.map(e=>`<div class="event ${e.date<today()?"overdue":""}"><b>${fmt(e.date)}</b><br>${esc(e.loan.name)} — ${e.kind}<br><small>${e.loan.loan_type==="emi"?money(e.loan.emi):money(interest(e.loan))}</small></div>`).join(""):"<p>No scheduled payments.</p>"}</div>`);}$("calendarBox").innerHTML=months.join("");}
function populateSimulator(){const current=$("simLoan").value;$("simLoan").innerHTML=loans.filter(l=>l.loan_type==="emi").map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join("");if(current&&loans.some(l=>l.id===current))$("simLoan").value=current;}
function csvEscape(v){return `"${String(v??"").replace(/"/g,'""')}"`;}
function exportCSV(){const rows=[["Loan","Category","Loan Type","Payment Date","Amount","Payment Type","Note"]];loans.forEach(l=>ps(l.id).forEach(p=>{const n=parseNotes(l.notes);rows.push([l.name,n.category,l.loan_type,p.payment_date,p.amount,p.payment_type,p.note||""]);}));const blob=new Blob([rows.map(r=>r.map(csvEscape).join(",")).join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="my-loan-tracker-v4.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
async function backup(){const data={version:4,exported:new Date().toISOString(),loans:loans.map(l=>({...l,payments:ps(l.id)}))};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="my-loan-tracker-v4-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
async function restore(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.loans))throw Error("Invalid backup file.");if(!confirm(`Restore ${data.loans.length} loans? Existing data will not be deleted; duplicate names may result.`))return;for(const old of data.loans){const {id,...lp}=old;delete lp.payments;delete lp.created_at;const ins=await sb.from("loans").insert(lp).select("id").single();if(ins.error)throw ins.error;for(const p of old.payments||[]){const {id,...pp}=p;delete pp.created_at;pp.loan_id=ins.data.id;const r=await sb.from("payments").insert(pp);if(r.error)throw r.error;}}await load();notice("Backup restored.");}catch(e){notice(e.message||"Could not restore backup.");}}
async function reminders(){if(!("Notification"in window))return notice("Browser notifications are not supported here.");const p=await Notification.requestPermission();if(p!=="granted")return notice("Notification permission was not granted.");const upcoming=loans.filter(l=>l.due_date).map(l=>({l,days:Math.ceil((new Date(l.due_date)-new Date(today()))/86400000)})).filter(x=>x.days>=0&&x.days<=7);if(upcoming.length)new Notification("Loan payment reminder",{body:upcoming.map(x=>`${x.l.name}: ${x.days===0?"due today":`due in ${x.days} day${x.days===1?"":"s"}`}`).join("\n")});else notice("Reminders enabled. No payment is due within 7 days.");localStorage.setItem("loanReminderEnabled","1");localStorage.setItem("loanReminderLast",today());}
$("type").onchange=fields;$("add").onclick=showAdd;$("cancelLoan").onclick=()=>$("loanSec").classList.add("hidden");$("cancelPay").onclick=()=>$("paySec").classList.add("hidden");$("closeSchedule").onclick=()=>$("scheduleSec").classList.add("hidden");$("closeHistory").onclick=()=>$("historySec").classList.add("hidden");$("closeSim").onclick=()=>$("simSec").classList.add("hidden");$("search").oninput=render;$("filter").onchange=render;$("categoryFilter").onchange=render;$("amount").oninput=updateEmiSplit;$("runSim").onclick=runSimulator;$("csvBtn").onclick=exportCSV;$("backup").onclick=backup;$("restoreBtn").onclick=()=>$("restoreFile").click();$("restoreFile").onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=""};$("remindersBtn").onclick=reminders;$("printBtn").onclick=()=>window.print();
$("loanForm").onsubmit=async e=>{e.preventDefault();const type=$("type").value,p={name:$("name").value.trim(),loan_type:type,principal:Number($("principal").value),interest_rate:Number($("rate").value),emi:Number($("emi").value)||0,frequency:$("frequency").value,due_date:(type==="emi"?$("emiDueDate").value:$("dueDate").value)||null,notes:packNotes($("category").value,$("notes").value.trim())};const r=editingLoanId?await sb.from("loans").update(p).eq("id",editingLoanId):await sb.from("loans").insert(p);if(r.error)return notice(r.error.message);$("loanSec").classList.add("hidden");await load();};
$("payForm").onsubmit=async e=>{e.preventDefault();const id=$("payLoanId").value,l=loans.find(x=>x.id===id),amt=Number($("amount").value);if(!l||!(amt>0))return;const date=$("payDate").value,note=$("payNote").value.trim();if(l.loan_type==="emi"){const mr=Number(l.interest_rate)/1200,ip=Math.min(amt,Number(l.principal)*mr),pp=Math.max(0,amt-ip),g=crypto.randomUUID(),rows=[];if(ip>0)rows.push({loan_id:id,payment_date:date,amount:ip,payment_type:"interest",note:`[[group:${g}]]EMI interest${note?" — "+note:""}`});if(pp>0)rows.push({loan_id:id,payment_date:date,amount:pp,payment_type:"principal",note:`[[group:${g}]]EMI principal${note?" — "+note:""}`});const r=await sb.from("payments").insert(rows);if(r.error)return notice(r.error.message);const u=await sb.from("loans").update({principal:Math.max(0,Number(l.principal)-pp),due_date:Number(l.principal)-pp>0?addMonths(l.due_date||date,1):null}).eq("id",id);if(u.error)return notice(u.error.message);}else{const type=$("payType").value,r=await sb.from("payments").insert({loan_id:id,payment_date:date,amount:amt,payment_type:type,note:note||null});if(r.error)return notice(r.error.message);if(type==="principal"){const u=await sb.from("loans").update({principal:Math.max(0,Number(l.principal)-amt)}).eq("id",id);if(u.error)return notice(u.error.message);}}$("paySec").classList.add("hidden");await load();};
$("toggle").onclick=()=>{signup=!signup;$("authTitle").textContent=signup?"Create account":"Sign in";$("authBtn").textContent=signup?"Create account":"Sign in";$("password").autocomplete=signup?"new-password":"current-password";$("toggle").textContent=signup?"Already have an account? Sign in":"Create a new account";};
$("authForm").onsubmit=async e=>{e.preventDefault();if(!sb){$("authMsg").textContent="Supabase is not configured. Keep your existing config.js.";return;}$("authBtn").disabled=true;$("authMsg").textContent=signup?"Creating account…":"Signing in…";try{const email=$("email").value.trim(),password=$("password").value,r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(signup&&!r.data.session){$("authMsg").textContent="Account created. Check your email, confirm it, then sign in.";return;}if(r.data.session?.user)await show(r.data.session.user);}catch(err){$("authMsg").textContent=err.message||String(err);}finally{$("authBtn").disabled=false;}};
async function show(u){$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("userArea").classList.remove("hidden");$("userEmail").textContent=u.email||"";await load();if(localStorage.getItem("loanReminderEnabled")==="1"&&localStorage.getItem("loanReminderLast")!==today())reminders();}
$("logoutBtn").onclick=async()=>{if(sb)await sb.auth.signOut();$("app").classList.add("hidden");$("userArea").classList.add("hidden");$("auth").classList.remove("hidden");};
async function init(){if(!configured){notice("Supabase setup required: keep your working config.js and the Supabase script.");return;}try{const r=await sb.auth.getSession();if(r.error)throw r.error;if(r.data.session?.user)await show(r.data.session.user);}catch(e){$("authMsg").textContent=e.message||String(e);}sb.auth.onAuthStateChange((event,s)=>{if(event==="SIGNED_IN"&&s?.user)show(s.user);});}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});init();
