/* My Loan Tracker V4 - built on the working V3.5 database schema. */
const configured = typeof window.SUPABASE_URL === "string" && typeof window.SUPABASE_ANON_KEY === "string" && !window.SUPABASE_URL.includes("YOUR_") && !window.SUPABASE_ANON_KEY.includes("YOUR_") && typeof window.supabase !== "undefined";
const sb = configured ? window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY) : null;
let loans=[], paymentCache={}, editingLoan=null, paymentEdit=null, signup=false, currentUser=null;
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>d?new Date(d+"T00:00:00").toLocaleDateString("en-IN"):"Not set";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const frequencyMonths=f=>f==="quarterly"?3:f==="halfyearly"?6:12;
const loanInterest=l=>Number(l.principal||0)*Number(l.interest_rate||0)/100/(l.frequency==="quarterly"?4:l.frequency==="halfyearly"?2:1);
const paymentsFor=id=>paymentCache[id]||[];
function notice(t){$("notice").textContent=t;$("notice").classList.remove("hidden");setTimeout(()=>$("notice").classList.add("hidden"),6000)}
function addMonths(ds,months){const d=new Date((ds||today())+"T00:00:00"),day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()!==day)d.setDate(0);return d.toISOString().slice(0,10)}
function daysBetween(a,b){return Math.round((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000)}
function isOverdue(l){return !!(l.due_date&&l.due_date<today())}
function isSoon(l){return !!(l.due_date&&l.due_date>=today()&&daysBetween(today(),l.due_date)<=30)}
function principalPaid(l){return paymentsFor(l.id).filter(p=>p.payment_type==="principal").reduce((s,p)=>s+Number(p.amount||0),0)}
function interestPaid(l){return paymentsFor(l.id).filter(p=>p.payment_type==="interest").reduce((s,p)=>s+Number(p.amount||0),0)}
function originalPrincipal(l){return Math.max(0,Number(l.principal||0)+principalPaid(l))}
function progress(l){const o=originalPrincipal(l);return o?Math.min(100,Math.max(0,principalPaid(l)/o*100)):0}
function monthlyRate(l){return Number(l.interest_rate||0)/100/12}
function fields(){const e=$("type").value==="emi";$("emiFields").classList.toggle("hidden",!e);$("intFields").classList.toggle("hidden",e);$("emiDateFields").classList.toggle("hidden",!e);$("emi").required=e}
function projectedSchedule(l,extra=0){
  if(!l||l.loan_type!=="emi")return {rows:[],interest:0,payments:0};
  let bal=Math.max(0,Number(l.principal)||0), date=l.due_date||today(), n=0,totalI=0,totalP=0,rows=[];
  const paymentBase=Math.max(0,Number(l.emi)||0)+Math.max(0,Number(extra)||0), rate=monthlyRate(l);
  if(paymentBase<=0)return {rows,interest:0,payments:0};
  while(bal>0.005&&n<600){n++;const opening=bal,i=opening*rate,p=Math.min(paymentBase,opening+i),pr=Math.max(0,p-i);bal=Math.max(0,opening-pr);totalI+=i;totalP+=p;rows.push({n,date,opening,interest:i,payment:p,principal:pr,closing:bal});date=addMonths(date,1)}
  return {rows,interest:totalI,payments:totalP};
}
async function load(){
  if(!sb)return;
  const r=await sb.from("loans").select("*").order("created_at");
  if(r.error){notice(r.error.message);return}
  loans=r.data||[];paymentCache={};
  if(loans.length){const p=await sb.from("payments").select("*").in("loan_id",loans.map(l=>l.id)).order("payment_date",{ascending:false});if(p.error){notice(p.error.message);return}for(const row of p.data||[])(paymentCache[row.loan_id]??=[]).push(row)}
  render();checkDueNotifications();
}
function filteredLoans(){const q=$("search").value.trim().toLowerCase(),f=$("filter").value;return loans.filter(l=>{const m=!q||l.name.toLowerCase().includes(q)||(l.notes||"").toLowerCase().includes(q);const t=f==="all"||l.loan_type===f||(f==="overdue"&&isOverdue(l));return m&&t})}
function nextDueLoan(){return loans.filter(l=>l.due_date).sort((a,b)=>a.due_date.localeCompare(b.due_date))[0]}
function debtFreeDate(){let dates=[];for(const l of loans.filter(x=>x.loan_type==="emi"&&Number(x.principal)>0)){const s=projectedSchedule(l);if(s.rows.length)dates.push(s.rows.at(-1).date)}return dates.sort().at(-1)||null}
function render(){
  const total=loans.reduce((s,l)=>s+Number(l.principal||0),0),emiOutstanding=loans.filter(l=>l.loan_type==="emi").reduce((s,l)=>s+Number(l.principal||0),0),monthly=loans.filter(l=>l.loan_type==="emi").reduce((s,l)=>s+Number(l.emi||0),0),intOutstanding=loans.filter(l=>l.loan_type==="interest").reduce((s,l)=>s+Number(l.principal||0),0),due=loans.filter(l=>l.loan_type==="interest").reduce((s,l)=>s+loanInterest(l),0),paid=loans.reduce((s,l)=>s+interestPaid(l),0);
  $("total").textContent=money(total);$("monthlyEmi").textContent=money(monthly);$("intTotal").textContent=money(intOutstanding);$("dueTotal").textContent=money(due);$("paidTotal").textContent=money(paid);$("overdueTotal").textContent=loans.filter(isOverdue).length;
  const orig=loans.reduce((s,l)=>s+originalPrincipal(l),0),pp=loans.reduce((s,l)=>s+principalPaid(l),0),pct=orig?Math.min(100,pp/orig*100):0;
  $("progressText").textContent=pct.toFixed(1)+"%";$("progressBar").style.width=pct+"%";$("progressDetail").textContent=orig?`${money(pp)} principal repaid of ${money(orig)}`:"No principal payments yet";
  const df=debtFreeDate();$("debtFreeDate").textContent=df?fmt(df):"—";$("debtFreeDetail").textContent=df?"Projected from current EMI loans":"No EMI payoff schedule available";
  const nd=nextDueLoan();$("nextDue").textContent=nd?fmt(nd.due_date):"—";$("nextDueDetail").textContent=nd?`${nd.name} • ${nd.loan_type==="emi"?money(nd.emi):money(loanInterest(nd))}`:"No upcoming payments";
  const box=$("loans");box.innerHTML="";const list=filteredLoans();
  if(!list.length){box.innerHTML=`<div class="card empty">${loans.length?"No loans match your search/filter.":"No loans yet. Click + Add Loan to begin."}</div>`;return}
  for(const l of list){
    const ps=paymentsFor(l.id),ip=interestPaid(l),ppaid=principalPaid(l),pctLoan=progress(l),dueI=l.loan_type==="interest"?loanInterest(l):0;
    const status=l.loan_type==="interest"?(isOverdue(l)?'<span class="badge overdue">Overdue</span>':isSoon(l)?'<span class="badge soon">Due soon</span>':'<span class="badge ok">On track</span>'):'<span class="badge">Monthly EMI</span>';
    const a=document.createElement("article");a.className="card loan";
    const detail=l.loan_type==="emi"?`Monthly EMI: <b>${money(l.emi)}</b><br>Rate: <b>${esc(l.interest_rate)}% p.a.</b><br>Next EMI: <b>${fmt(l.due_date)}</b>`:`Rate: <b>${esc(l.interest_rate)}% p.a.</b><br>${esc(l.frequency)} interest: <b>${money(dueI)}</b><br>Next due: <b>${fmt(l.due_date)}</b> ${status}`;
    a.innerHTML=`<div class="loanTop"><div><h3>${esc(l.name)}</h3><span class="badge">${l.loan_type==="emi"?"EMI Loan":"Interest Only"}</span></div><strong class="balance">${money(l.principal)}</strong></div><div class="details">${detail}</div><div class="payment-summary"><div class="mini">Interest paid<b>${money(ip)}</b></div><div class="mini">Principal paid<b>${money(ppaid)}</b></div><div class="mini">${l.loan_type==="interest"?"Current interest":"Next EMI"}<b>${l.loan_type==="interest"?money(dueI):money(l.emi)}</b></div></div><div class="loan-progress"><small>Principal repaid: ${pctLoan.toFixed(1)}%</small><div class="progress"><i style="width:${pctLoan}%"></i></div></div><div class="actions"><button data-a="pay" type="button">Record Payment</button>${l.loan_type==="emi"?'<button data-a="schedule" type="button">Schedule</button><button data-a="sim" type="button">Simulator</button>':''}<button data-a="edit" type="button">Edit</button><button data-a="history" type="button">History</button><button data-a="del" class="danger" type="button">Delete</button></div><div class="history hidden"></div>`;
    a.querySelector('[data-a="pay"]').onclick=()=>showPay(l.id);a.querySelector('[data-a="edit"]').onclick=()=>showEdit(l.id);a.querySelector('[data-a="history"]').onclick=()=>toggleHistory(a,l.id);a.querySelector('[data-a="del"]').onclick=()=>deleteLoan(l.id);if(l.loan_type==="emi"){a.querySelector('[data-a="schedule"]').onclick=()=>showSchedule(l.id);a.querySelector('[data-a="sim"]').onclick=()=>showSimulator(l.id)}box.appendChild(a);
  }
}
function toggleHistory(card,id){
  const h=card.querySelector(".history");h.classList.toggle("hidden");if(h.classList.contains("hidden"))return;
  const ps=paymentsFor(id);if(!ps.length){h.innerHTML='<div>No payments recorded.</div>';return}
  const groups=new Map(), singles=[];
  for(const p of ps){const g=(p.note||"").match(/\[group:([^\]]+)\]/)?.[1];if(g){if(!groups.has(g))groups.set(g,[]);groups.get(g).push(p)}else singles.push(p)}
  const groupRows=[...groups.entries()].map(([g,rows])=>{const l=loans.find(x=>x.id===id);const total=rows.reduce((s,p)=>s+Number(p.amount||0),0),i=rows.filter(p=>p.payment_type==="interest").reduce((s,p)=>s+Number(p.amount||0),0),pr=rows.filter(p=>p.payment_type==="principal").reduce((s,p)=>s+Number(p.amount||0),0),p=rows[0],note=(p.note||"").replace(/\[group:[^\]]+\]\s*/,'').replace(/^EMI (interest|principal)\s*—?\s*/,'').trim();return `<div class="history-row"><div><b>${fmt(p.payment_date)}</b> — <b>${money(total)}</b> — EMI<br><small>Interest ${money(i)} • Principal ${money(pr)}${note?" • "+esc(note):""}</small></div><div class="history-actions"><button type="button" onclick="editPaymentGroup('${g}','${id}')">Edit EMI</button><button type="button" class="danger" onclick="deletePaymentGroup('${g}','${id}')">Delete EMI</button></div></div>`}).join("");
  const singleRows=singles.map(p=>{const label=p.payment_type==="interest"?"Interest":"Principal";return `<div class="history-row"><div><b>${fmt(p.payment_date)}</b> — <b>${money(p.amount)}</b> — ${label}<br><small>${esc(p.note||"")}</small></div><div class="history-actions"><button type="button" onclick="editPayment('${p.id}','${id}')">Edit</button><button type="button" class="danger" onclick="deletePayment('${p.id}','${id}')">Delete</button></div></div>`}).join("");
  h.innerHTML=groupRows+singleRows;
}
async function deleteLoan(id){if(!confirm("Delete this loan and all its payment history?"))return;const r=await sb.from("loans").delete().eq("id",id);if(r.error)notice(r.error.message);else{notice("Loan deleted");await load()}}
function hideSections(){["loanSec","paySec","scheduleSec","reportSec","calendarSec","simSec"].forEach(id=>$(id).classList.add("hidden"))}
function showAdd(){editingLoan=null;hideSections();$("loanTitle").textContent="Add Loan";$("loanForm").reset();$("type").value="interest";fields();$("loanSec").classList.remove("hidden");$("loanSec").scrollIntoView({behavior:"smooth",block:"start"})}
function showEdit(id){const l=loans.find(x=>x.id===id);if(!l)return;editingLoan=id;hideSections();$("loanTitle").textContent="Edit Loan";$("name").value=l.name;$("type").value=l.loan_type;$("principal").value=l.principal;$("rate").value=l.interest_rate;$("emi").value=l.emi||"";$("frequency").value=l.frequency||"yearly";$("dueDate").value=l.loan_type==="interest"?(l.due_date||""):"";$("emiDueDate").value=l.loan_type==="emi"?(l.due_date||""):"";$("notes").value=l.notes||"";fields();$("loanSec").classList.remove("hidden");$("loanSec").scrollIntoView({behavior:"smooth",block:"start"})}
function showPay(id){const l=loans.find(x=>x.id===id);if(!l)return;hideSections();$("payLoanId").value=id;$("payLoanName").textContent=l.name;$("payDate").value=today();$("amount").value=l.loan_type==="emi"?l.emi:"";$("payType").value="interest";$("payNote").value="";const e=l.loan_type==="emi";$("payTitle").textContent=e?"Record EMI Payment":"Record Payment";$("payTypeWrap").classList.toggle("hidden",e);$("emiPaymentHelp").classList.toggle("hidden",!e);$("emiSplit").classList.toggle("hidden",!e);if(e)updateEmiSplit();$("paySec").classList.remove("hidden");$("paySec").scrollIntoView({behavior:"smooth",block:"start"})}
function updateEmiSplit(){const l=loans.find(x=>x.id===$("payLoanId").value);if(!l)return;const amt=Number($("amount").value)||0,i=Math.min(amt,Math.max(0,monthlyRate(l)*Number(l.principal||0))),p=Math.max(0,amt-i);$("emiInterest").textContent=money(i);$("emiPrincipal").textContent=money(p)}
function showSchedule(id){const l=loans.find(x=>x.id===id),s=projectedSchedule(l);if(!l)return;hideSections();let html="";if(!s.rows.length)html='<div class="card">Set a positive EMI to generate the schedule.</div>';else html=`<div class="card"><div class="schedule-head"><div class="mini">Current balance<b>${money(l.principal)}</b></div><div class="mini">Future interest<b>${money(s.interest)}</b></div><div class="mini">Future payments<b>${money(s.payments)}</b></div></div><div class="schedule-note">Assumes the current interest rate and EMI stay unchanged. Estimated ${s.rows.length} payments.</div><div style="overflow:auto"><table class="schedule-table"><thead><tr><th>#</th><th>Date</th><th>Opening</th><th>Interest</th><th>Payment</th><th>Principal</th><th>Closing</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${r.n}</td><td>${fmt(r.date)}</td><td>${money(r.opening)}</td><td>${money(r.interest)}</td><td>${money(r.payment)}</td><td>${money(r.principal)}</td><td>${money(r.closing)}</td></tr>`).join("")}</tbody></table></div></div>`;$("scheduleBox").innerHTML=html;$("scheduleSec").classList.remove("hidden");$("scheduleSec").scrollIntoView({behavior:"smooth",block:"start"})}
function showSimulator(id){const l=loans.find(x=>x.id===id);if(!l)return;hideSections();$("simBox").innerHTML=`<p class="note">Simulate an extra amount paid toward principal every month. This does not change your real loan.</p><div class="sim-form"><label>Extra monthly principal (₹)<input id="simExtra" type="number" min="0" step=".01" value="500"></label><label>Or one-time principal (₹)<input id="simOne" type="number" min="0" step=".01" value="0"></label><button id="runSim" class="primary" type="button">Calculate</button></div><div id="simResult"></div>`;$("simSec").classList.remove("hidden");$("runSim").onclick=()=>runSimulator(id);runSimulator(id)}
function runSimulator(id){const l=loans.find(x=>x.id===id);const extra=Number($("simExtra").value)||0,one=Math.min(Number($("simOne").value)||0,Number(l.principal)||0),base={...l,principal:Math.max(0,Number(l.principal||0)-one)},normal=projectedSchedule(l,0),sim=projectedSchedule(base,extra);if(!normal.rows.length||!sim.rows.length){$("simResult").innerHTML='<p class="note">A valid EMI is required.</p>';return}const savedMonths=normal.rows.length-sim.rows.length,savedInterest=Math.max(0,normal.interest-sim.interest);$("simResult").innerHTML=`<div class="sim-result"><div class="mini">Normal payoff<b>${fmt(normal.rows.at(-1).date)}</b></div><div class="mini">Simulated payoff<b>${fmt(sim.rows.at(-1).date)}</b></div><div class="mini">Time saved<b>${savedMonths} month${savedMonths===1?"":"s"}</b></div><div class="mini">Normal future interest<b>${money(normal.interest)}</b></div><div class="mini">Simulated future interest<b>${money(sim.interest)}</b></div><div class="mini">Interest saved<b>${money(savedInterest)}</b></div></div>`}
function showReports(){hideSections();const allI=loans.reduce((s,l)=>s+interestPaid(l),0),allP=loans.reduce((s,l)=>s+principalPaid(l),0),futureI=loans.filter(l=>l.loan_type==="emi").reduce((s,l)=>s+projectedSchedule(l).interest,0);const year=new Date().getFullYear();const months=[];for(let m=0;m<12;m++){const key=`${year}-${String(m+1).padStart(2,"0")}`;let i=0,p=0;for(const l of loans)for(const x of paymentsFor(l.id)){if(x.payment_date.startsWith(key)){if(x.payment_type==="interest")i+=Number(x.amount);else p+=Number(x.amount)}}months.push({key,i,p,total:i+p})}const rows=months.map(x=>`<tr><td>${new Date(x.key+"-01T00:00:00").toLocaleString("en-IN",{month:"short"})}</td><td>${money(x.i)}</td><td>${money(x.p)}</td><td>${money(x.total)}</td></tr>`).join("");const years={};for(const l of loans)for(const x of paymentsFor(l.id)){const y=(x.payment_date||"").slice(0,4)||"Unknown";(years[y]??={i:0,p:0});if(x.payment_type==="interest")years[y].i+=Number(x.amount||0);else years[y].p+=Number(x.amount||0)}const yearRows=Object.keys(years).sort((a,b)=>b.localeCompare(a)).map(y=>`<tr><td>${y}</td><td>${money(years[y].i)}</td><td>${money(years[y].p)}</td><td>${money(years[y].i+years[y].p)}</td></tr>`).join("");$("reportBox").innerHTML=`<div class="card"><div class="report-grid"><div class="mini">Principal paid<b>${money(allP)}</b></div><div class="mini">Interest paid<b>${money(allI)}</b></div><div class="mini">Future EMI interest<b>${money(futureI)}</b></div><div class="mini">Total payments<b>${money(allI+allP)}</b></div></div></div><div class="card report-month"><h3>${year} monthly payments</h3><div style="overflow:auto"><table class="report-table"><thead><tr><th>Month</th><th>Interest</th><th>Principal</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table></div></div><div class="card report-month"><h3>Yearly payments</h3><div style="overflow:auto"><table class="report-table"><thead><tr><th>Year</th><th>Interest</th><th>Principal</th><th>Total</th></tr></thead><tbody>${yearRows||'<tr><td colspan="4">No payment history yet.</td></tr>'}</tbody></table></div></div><div class="card"><h3>Loan interest analysis</h3><div style="overflow:auto"><table class="report-table"><thead><tr><th>Loan</th><th>Interest paid</th><th>Current interest</th><th>Future EMI interest</th></tr></thead><tbody>${loans.map(l=>`<tr><td>${esc(l.name)}</td><td>${money(interestPaid(l))}</td><td>${l.loan_type==="interest"?money(loanInterest(l)):"—"}</td><td>${l.loan_type==="emi"?money(projectedSchedule(l).interest):"—"}</td></tr>`).join("")}</tbody></table></div></div>`;$("reportSec").classList.remove("hidden");$("reportSec").scrollIntoView({behavior:"smooth",block:"start"})}
function showCalendar(){hideSections();const end=addMonths(today(),3),items=loans.filter(l=>l.due_date&&l.due_date<=end).sort((a,b)=>a.due_date.localeCompare(b.due_date));$("calendarBox").innerHTML=`<div class="card"><p class="note">Upcoming scheduled payments through ${fmt(end)}. Interest-only amounts are based on the current principal and rate.</p>${items.length?items.map(l=>`<div class="calendar-item"><div><div class="calendar-date">${fmt(l.due_date)}</div><div class="calendar-type">${esc(l.name)} • ${l.loan_type==="emi"?"EMI":"Interest"}</div></div><b>${money(l.loan_type==="emi"?l.emi:loanInterest(l))}</b></div>`).join(""):'<div class="empty">No scheduled payments in the next 3 months.</div>'}</div>`;$("calendarSec").classList.remove("hidden");$("calendarSec").scrollIntoView({behavior:"smooth",block:"start"})}
function csvCell(v){return `"${String(v??"").replace(/"/g,'""')}"`}
function exportCSV(){const rows=[["Loan","Loan type","Current principal","Rate","EMI","Payment date","Payment amount","Payment type","Note"]];for(const l of loans){const ps=paymentsFor(l.id);if(!ps.length)rows.push([l.name,l.loan_type,l.principal,l.interest_rate,l.emi,"","","",l.notes||""]);else for(const p of ps)rows.push([l.name,l.loan_type,l.principal,l.interest_rate,l.emi,p.payment_date,p.amount,p.payment_type,p.note||""])}const blob=new Blob([rows.map(r=>r.map(csvCell).join(",")).join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="loan-tracker-v4.csv";a.click();URL.revokeObjectURL(url)}
async function backup(){const data={version:4,exported:new Date().toISOString(),loans:loans.map(l=>({...l,payments:paymentsFor(l.id)}))};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="loan-tracker-v4-backup.json";a.click();URL.revokeObjectURL(url)}
async function editPayment(paymentId,loanId){const p=paymentsFor(loanId).find(x=>x.id===paymentId);if(!p)return;const l=loans.find(x=>x.id===loanId);paymentEdit={paymentId,loanId};hideSections();$("payTitle").textContent="Edit Payment";$("payLoanId").value=loanId;$("payLoanName").textContent=l.name;$("payDate").value=p.payment_date;$("amount").value=p.amount;$("payType").value=p.payment_type;$("payNote").value=(p.note||"").replace(/\[group:[^\]]+\]\s*/,'');$("payTypeWrap").classList.remove("hidden");$("emiPaymentHelp").classList.add("hidden");$("emiSplit").classList.add("hidden");$("paySec").classList.remove("hidden");$("paySec").scrollIntoView({behavior:"smooth",block:"start"})}
async function editPaymentGroup(group,loanId){const ps=paymentsFor(loanId).filter(p=>(p.note||"").includes(`[group:${group}]`));if(!ps.length)return;const l=loans.find(x=>x.id===loanId);const oldI=ps.filter(p=>p.payment_type==="interest").reduce((s,p)=>s+Number(p.amount),0),oldP=ps.filter(p=>p.payment_type==="principal").reduce((s,p)=>s+Number(p.amount),0),date=ps[0].payment_date,note=(ps[0].note||"").replace(/\[group:[^\]]+\]\s*/,'').replace(/^EMI (interest|principal)\s*—?\s*/,'').trim();paymentEdit={group,loanId,oldI,oldP};hideSections();$("payTitle").textContent="Edit EMI Payment";$("payLoanId").value=loanId;$("payLoanName").textContent=l.name;$("payDate").value=date;$("amount").value=(oldI+oldP).toFixed(2);$("payNote").value=note;$("payTypeWrap").classList.add("hidden");$("emiPaymentHelp").classList.remove("hidden");$("emiSplit").classList.remove("hidden");$("paySec").classList.remove("hidden");updateEmiSplitForBalance(l,oldP);$("paySec").scrollIntoView({behavior:"smooth",block:"start"})}
function updateEmiSplitForBalance(l,oldPrincipal){const amount=Number($("amount").value)||0,bal=Number(l.principal||0)+Number(oldPrincipal||0),i=Math.min(amount,bal*monthlyRate(l)),p=Math.max(0,amount-i);$("emiInterest").textContent=money(i);$("emiPrincipal").textContent=money(p)}
async function deletePayment(id,loanId){const p=paymentsFor(loanId).find(x=>x.id===id),l=loans.find(x=>x.id===loanId);if(!p||!l||!confirm("Delete this payment?"))return;if(p.payment_type==="principal"){const u=await sb.from("loans").update({principal:Number(l.principal)+Number(p.amount)}).eq("id",loanId);if(u.error){notice(u.error.message);return}}const r=await sb.from("payments").delete().eq("id",id);if(r.error)notice(r.error.message);else await load()}
async function deletePaymentGroup(group,loanId){const ps=paymentsFor(loanId).filter(p=>(p.note||"").includes(`[group:${group}]`)),l=loans.find(x=>x.id===loanId),oldP=ps.filter(p=>p.payment_type==="principal").reduce((s,p)=>s+Number(p.amount),0);if(!ps.length||!confirm("Delete this EMI payment? The principal portion will be restored."))return;if(oldP){const u=await sb.from("loans").update({principal:Number(l.principal)+oldP,due_date:addMonths(l.due_date||today(),-1)}).eq("id",loanId);if(u.error){notice(u.error.message);return}}const r=await sb.from("payments").delete().in("id",ps.map(p=>p.id));if(r.error)notice(r.error.message);else await load()}
window.editPayment=editPayment;window.editPaymentGroup=editPaymentGroup;window.deletePayment=deletePayment;window.deletePaymentGroup=deletePaymentGroup;
$("type").onchange=fields;$("add").onclick=showAdd;$("cancelLoan").onclick=()=>$("loanSec").classList.add("hidden");$("cancelPay").onclick=()=>{paymentEdit=null;$("paySec").classList.add("hidden")};$("closeSchedule").onclick=()=>$("scheduleSec").classList.add("hidden");$("search").oninput=render;$("filter").onchange=render;$("amount").oninput=()=>{updateEmiSplit();if(paymentEdit?.group){const l=loans.find(x=>x.id===paymentEdit.loanId);if(l)updateEmiSplitForBalance(l,paymentEdit.oldP)}};
$("loanForm").onsubmit=async e=>{e.preventDefault();const p={name:$("name").value.trim(),loan_type:$("type").value,principal:Number($("principal").value),interest_rate:Number($("rate").value),emi:Number($("emi").value)||0,frequency:$("frequency").value,due_date:($("type").value==="emi"?$("emiDueDate").value:$("dueDate").value)||null,notes:$("notes").value.trim()||null};if(!p.name){notice("Enter a loan name");return}const r=editingLoan?await sb.from("loans").update(p).eq("id",editingLoan):await sb.from("loans").insert(p);if(r.error)notice(r.error.message);else{editingLoan=null;$("loanSec").classList.add("hidden");await load()}};
$("payForm").onsubmit=async e=>{e.preventDefault();const id=$("payLoanId").value,l=loans.find(x=>x.id===id),amt=Number($("amount").value)||0;if(!l||amt<=0)return;try{
  if(paymentEdit?.group){
    const group=paymentEdit.group,oldP=paymentEdit.oldP,oldI=paymentEdit.oldI,restored=Number(l.principal)+oldP,rate=monthlyRate(l),i=Math.min(amt,restored*rate),p=Math.max(0,amt-i),rows=paymentsFor(id).filter(x=>(x.note||"").includes(`[group:${group}]`));
    const u=await sb.from("loans").update({principal:Math.max(0,restored-p),due_date:Math.max(0,restored-p)>0?addMonths($("payDate").value,1):null}).eq("id",id);if(u.error)throw u.error;
    const del=await sb.from("payments").delete().in("id",rows.map(x=>x.id));if(del.error)throw del.error;
    const groupNote=`[group:${group}]`;const ins=[];if(i>0)ins.push({loan_id:id,payment_date:$("payDate").value,amount:i,payment_type:"interest",note:`${groupNote} EMI interest${$("payNote").value.trim()?" — "+$("payNote").value.trim():""}`});if(p>0)ins.push({loan_id:id,payment_date:$("payDate").value,amount:p,payment_type:"principal",note:`${groupNote} EMI principal${$("payNote").value.trim()?" — "+$("payNote").value.trim():""}`});if(ins.length){const x=await sb.from("payments").insert(ins);if(x.error)throw x.error}
  }else if(paymentEdit?.paymentId){
    const old=paymentsFor(id).find(x=>x.id===paymentEdit.paymentId),oldType=old.payment_type,newType=$("payType").value,oldAmt=Number(old.amount),newAmt=amt;
    let newPrincipal=Number(l.principal);if(oldType==="principal")newPrincipal+=oldAmt;if(newType==="principal")newPrincipal-=newAmt;if(newPrincipal<0)throw new Error("Principal payment cannot exceed the current principal.");
    const r=await sb.from("payments").update({payment_date:$("payDate").value,amount:newAmt,payment_type:newType,note:$("payNote").value.trim()||null}).eq("id",old.id);if(r.error)throw r.error;if(newPrincipal!==Number(l.principal)){const u=await sb.from("loans").update({principal:newPrincipal}).eq("id",id);if(u.error)throw u.error}
  }else if(l.loan_type==="emi"){
    const i=Math.min(amt,Number(l.principal)*monthlyRate(l)),p=Math.max(0,amt-i),group=crypto.randomUUID?crypto.randomUUID():String(Date.now()),note=$("payNote").value.trim(),rows=[];if(i>0)rows.push({loan_id:id,payment_date:$("payDate").value,amount:i,payment_type:"interest",note:`[group:${group}] EMI interest${note?" — "+note:""}`});if(p>0)rows.push({loan_id:id,payment_date:$("payDate").value,amount:p,payment_type:"principal",note:`[group:${group}] EMI principal${note?" — "+note:""}`});if(rows.length){const r=await sb.from("payments").insert(rows);if(r.error)throw r.error}const np=Math.max(0,Number(l.principal)-p),u=await sb.from("loans").update({principal:np,due_date:np>0?addMonths(l.due_date||$("payDate").value,1):null}).eq("id",id);if(u.error)throw u.error;
  }else{
    const type=$("payType").value;if(type==="principal"&&amt>Number(l.principal))throw new Error("Principal payment cannot exceed the current principal.");const r=await sb.from("payments").insert({loan_id:id,payment_date:$("payDate").value,amount:amt,payment_type:type,note:$("payNote").value.trim()||null});if(r.error)throw r.error;if(type==="principal"){const u=await sb.from("loans").update({principal:Math.max(0,Number(l.principal)-amt)}).eq("id",id);if(u.error)throw u.error}else if(type==="interest"&&amt>=loanInterest(l)-0.01){const next=addMonths(l.due_date||$("payDate").value,frequencyMonths(l.frequency));const u=await sb.from("loans").update({due_date:next}).eq("id",id);if(u.error)throw u.error}
  }
  paymentEdit=null;$("paySec").classList.add("hidden");notice("Payment saved");await load();
}catch(err){notice(err.message||String(err))}};
$("toggle").onclick=e=>{e.preventDefault();signup=!signup;$("authTitle").textContent=signup?"Create account":"Sign in";$("authBtn").textContent=signup?"Create account":"Sign in";$("password").autocomplete=signup?"new-password":"current-password";$("toggle").textContent=signup?"Already have an account? Sign in":"Create a new account"};
$("authForm").onsubmit=async e=>{e.preventDefault();if(!sb){$("authMsg").textContent="Supabase is not configured. Check config.js.";return}const btn=$("authBtn");btn.disabled=true;$("authMsg").textContent=signup?"Creating account…":"Signing in…";try{const email=$("email").value.trim(),password=$("password").value;const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(signup&&!r.data.session){$("authMsg").textContent="Account created. Check your email to confirm it, then sign in.";return}if(r.data.session?.user)await show(r.data.session.user)}catch(err){$("authMsg").textContent=err.message||String(err)}finally{btn.disabled=false}};
async function show(u){currentUser=u;$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("userArea").classList.remove("hidden");$("userEmail").textContent=u.email||"";await load()}
$("logoutBtn").onclick=async()=>{if(sb)await sb.auth.signOut()};$("reportBtn").onclick=showReports;$("calendarBtn").onclick=showCalendar;$("simBtn").onclick=()=>{const l=loans.find(x=>x.loan_type==="emi");if(l)showSimulator(l.id);else notice("Add an EMI loan first.")};$("exportCsv").onclick=exportCSV;$("backup").onclick=backup;$("printReport").onclick=()=>window.print();$("notifyBtn").onclick=async()=>{if(!("Notification"in window)){notice("This browser does not support notifications.");return}const p=await Notification.requestPermission();if(p==="granted"){localStorage.setItem("loanReminders","yes");notice("Reminders enabled. The app will check due items when opened.");checkDueNotifications()}else notice("Notification permission was not granted.")};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add("hidden"));
function checkDueNotifications(){if(localStorage.getItem("loanReminders")!=="yes"||!("Notification"in window)||Notification.permission!=="granted")return;const key=today();if(localStorage.getItem("loanReminderDate")===key)return;const due=loans.filter(l=>l.due_date&&daysBetween(today(),l.due_date)>=0&&daysBetween(today(),l.due_date)<=3);if(due.length){new Notification("My Loan Tracker",{body:`${due.length} loan payment${due.length>1?"s are":" is"} due within 3 days.`});localStorage.setItem("loanReminderDate",key)}}
async function init(){if(!configured){notice("Supabase is not configured. Keep your working config.js from V3.5.");return}try{const r=await sb.auth.getSession();if(r.error)throw r.error;if(r.data.session?.user)await show(r.data.session.user)}catch(err){$("authMsg").textContent=err.message||String(err)}sb.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_IN"&&session?.user){show(session.user)}else if(event==="SIGNED_OUT"){currentUser=null;location.reload()}})}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
init();
